services:
  backend:
    build: ./backend
    networks:
      - backend_redis_network
      - frontend_backend_network

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    networks:
      - frontend_backend_network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend_redis_network

volumes:
  redis_data:

networks:
  backend_redis_network:
    driver: bridge
  frontend_backend_network:
    driver: bridge
